/**
 * exports HTTP status codes
 */

const HTTPStatus = Object.freeze({
  ABORTED: 0,
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTI_STATUS: 207,
  ALREADY_REPORTED: 208,
  IM_USED: 226,
  MULTIPLE_CHOICES: 300,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  GONE: 410,
  UNPROCESSABLE_ENTITY: 422,
  SERVICE_UNAVAILABLE: 503,
})

export const successCodes = [
  HTTPStatus.OK,
  HTTPStatus.CREATED,
  HTTPStatus.ACCEPTED,
  HTTPStatus.NON_AUTHORITATIVE_INFORMATION,
  HTTPStatus.NO_CONTENT,
  HTTPStatus.RESET_CONTENT,
  HTTPStatus.PARTIAL_CONTENT,
  HTTPStatus.MULTI_STATUS,
  HTTPStatus.ALREADY_REPORTED,
  HTTPStatus.IM_USED,
]

export default HTTPStatus
