export const EVENT_UPDATE_CHART_DISPATCHED = 'ENERGY::UPDATE_CHART_DISPATCHED'
export const EVENT_UPDATE_ANNOTATION_DISPATCHED =
  'ENERGY::UPDATE_ANNOTATION_DISPATCHED'
export const EVENT_FETCH_DATA_STARTED = 'ENERGY::FETCH_DATA_STARTED'
export const EVENT_FETCH_DATA_FINISHED = 'ENERGY::FETCH_DATA_FINISHED'
