export const SET_SETTLED = 'setSettled'
export const SET_IMAGE = 'setImage'
export const SET_CODE = 'setCode'
export const SET_OPTIONS = 'setOptions'
export const SET_CODE1 = 'setCode1'
export const SET_CODE2 = 'setCode2'
export const SET_CODE1_VISIBILITY = 'setCode1Visibility'
export const SET_CODE2_VISIBILITY = 'setCode2Visibility'
