export const SET_STATION = 'setStation'
export const SET_TYPE = 'setType'
export const SET_SAMPLING = 'setSampling'
export const SET_MID_MODE = 'setMidMode'
export const SET_FILTER_DATA_TYPE = 'setDataType'
export const SET_AUTO_UPDATE = 'setAutoUpdate'
